### ISSUE TITLE
弹出层 双击关闭

### ISSUE THREAD

**Issue by Yannyezixin** [Yannyezixin/fg-demo#2]
https://github.com/Yannyezixin/fg-demo/blob/gh-pages/asset/js/vlayer-2.js#L19-L24
 双击 yes / no 按钮 ， 弹出层display 属性没有变为none;

问题重现:

http://youbookee.com/fg-demo/modal/modal2.html

**Comment by Yannyezixin** [comment]
@lemonpick  看看呗~

**Comment by zavven** [comment]
@Yannyezixin 我在chrome（36.0.1985.125 m）里看没有问题，弹出层display可以变为none。你的浏览器版本是多少？

**Comment by Yannyezixin** [comment]
@lemonpick 版本 41.0.2272.118 (64-bit)
双击喔。 你双击快点试试

**Comment by zavven** [comment]
问题应该出在toggle()，没有进行防重处理。双击会触发两次click事件，每一次click事件又都会触发toggle事件，toggle执行的速度比transitionend 快很多。
执行过程：
click:------------one-------------->two-------------------------------------------->
toggle:-----------display----------->none----------->display
transitionend:----1---------------------------------------------------------------->  0

**Comment by Yannyezixin** [comment]
@lemonpick 问题已解决
see 2fee0127bb6d5f3f43b5d086af6b205be1576f31

应该是这样吧：

click: ------------one------------------>two-------------->
toggle:----------display-------------->none-->display
transitionend---1-------------------->0-->0
---------------------------0.3s------------0s

toggle是在transitionend回调里执行，所以transitionend也是执行了两次。
直接 toggle改成hide

你有更好的解决方案吗？Thanks.
